export const REQUEST_CONTENT_LIST = 'REQUEST_CONTENT_LIST'
export const GET_CONTENT_LIST = 'GET_CONTENT_LIST'
export const GET_CONTENT_LIST_LENGTH = 'GET_CONTENT_LIST_LENGTH'
export const GET_CONTENT_LIST_FAILURE = 'GET_CONTENT_LIST_FAILURE'

export const GET_ALBUMS = 'GET_ALBUMS'
export const GET_ALBUM = 'GET_ALBUM'
export const GET_ALBUM_FAILURE = 'GET_ALBUM_FAILURE'

export const GET_MY_ALBUMS = 'GET_MY_ALBUMS'
export const GET_MY_ALBUMS_FAILURE = 'GET_MY_ALBUMS_FAILURE'

export const GET_MY_ALBUM = 'GET_MY_ALBUM'
export const GET_MY_ALBUM_FAILURE = 'GET_MY_ALBUM_FAILURE'

export const UPDATE_HEADLINE = 'UPDATE_HEADLINE'
export const GET_HEADLINE = 'GET_HEADLINE'

export const GET_MY_ARTICLES = 'GET_MY_ARTICLES'
export const GET_LIKES = 'GET_LIKES'
export const GET_ARTICLES = 'GET_ARTICLES'
export const GET_ARTICLE = 'GET_ARTICLE'

export const GET_TIMELINES = 'GET_TIMELINES'
export const GET_TIMELINE = 'GET_TIMELINE'

export const GET_USER = 'GET_USER'
export const GET_USER_FAILURE = 'GET_USER_FAILURE'
export const CLEAR_USER = 'CLEAR_USER'

export const GET_TAGS = 'GET_TAGS'
export const GET_TAGS_FAILURE = 'GET_TAGS_FAILURE'

export const GET_TAG_CONTENT_LIST = 'GET_TAG_CONTENT_LIST'
export const GET_TAG_CONTENT_LIST_FAILURE = 'GET_TAG_CONTENT_LIST_FAILURE'

export const GET_COMMENTS = 'GET_COMMENTS'

export const SUBMIT_COMMENT = 'SUBMIT_COMMENT'
export const SUBMIT_COMMENT_FAILURE = 'SUBMIT_COMMENT_FAILURE'

export const GET_ME = 'GET_ME'

export const LOGIN = 'LOGIN'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE'
export const GET_CAPTCHA = 'GET_CAPTCHA'

export const GET_QINIU_TOKEN = 'GET_QINIU_TOKEN'
export const GET_QINIU_TOKEN_FAILURE = 'GET_QINIU_TOKEN_FAILURE'
