FROM node:alpine

MAINTAINER 361509573@qq.com

WORKDIR /data/hicool

EXPOSE 5000

CMD ["node", "prod.server.js"]

# docker build -t hicool .
# docker run -it --rm -p 5000:5000 -v /Users/shouchao.zheng/Downloads/hicool:/data/hicool hicool /bin/sh